name: Cron CI

on: 
  schedule:
  - cron: "0/10 * * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: cron task
      run: curl "http://worldtimeapi.org/api/timezone/Asia/Shanghai"
