name: Cron CI

on: 
  schedule:
  - cron: "0/5 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: curl "http://worldtimeapi.org/api/timezone/Asia/Shanghai"
